### ISSUE TITLE
Problems compiling in Visual Studio 2019

### ISSUE THREAD

**Issue by RichardTND** [2bt/sid2sng#1]
I have been trying to compile the C++ project file in Visual Studio 2019. It results as no errors, but I cannot seem to make this program into an EXEcutable or test run it. A shame really as I had a tune I originally did in GoatTracker for one of my ongoing game projects, but I need to extract the "Get Ready and Game Over" jingles and use those in other tunes for the game project.

**Comment by MichaelTroelsen** [comment]
I had to add in main.cpp.
#ifdef _MSC_VER
#include <algorithm>
#endif
And in gsong.cpp
#ifdef _MSC_VER
#define _CRT_SECURE_NO_WARNINGS
#endif
Now it compile and build.
