### ISSUE TITLE
Does not work at all ...

### ISSUE THREAD

**Issue by napolitano** [2bt/sid2sng#10]
After compiling the tool and testing it against different SID files, I've got only error messages.

- Last_Ninja.sid: Segmentation fault
- Shades.sid: Segmentation fault
- Commando.sid: No freq table
- Ghosts_n_Goblins.sid: No freq table
- Kettle.sid: No freq table

SID-Files downloaded from HVSID-Collection. 

Without time consuming analysis it's not possible to find causes for that and maybe the files i picked may never be converted. However due to lack of documentation it's hard to guess with which types of files it might work. At least one reference file would probably help.

Would be great if the problem could be tracked down. Maybe it is OS related or maybe I'm using it wrong.

OS: macOS Ventura 13.1
CPU: Apple M2
RAM: 16 GByte
IDE: CLion 2022.3
CMake: 3.25.0

Please feel free to ask, if you need more information.

**Comment by 2bt** [comment]
The documentation, sparse as it is, does state that sid files need to have been generated via GoatTracker2. For all other files, this tool fails horribly.

**Comment by napolitano** [comment]
Well, you are right. One should at least read the first line. My fault. This issue should be closed/reverted/deleted. Sorry for that and thanks for your reply.
