### ISSUE TITLE
Problem with compiling

### ISSUE THREAD

**Issue by DeMOSic** [2bt/sid2sng#2]
when i try to compile the program with visual studio and cmake i get errors
when i make the projects with cmake i get no errors but when i try to compile the solution in vs 2019 i get alot of ferrors and warnings
so im wondering. what do you use for compiling this?
![vs](https://user-images.githubusercontent.com/82211203/137546739-d7832576-75e7-4194-bd10-8b943b56dd5a.png)

**Comment by That8BitChiptuneGuy** [comment]
also you should probably post a release of the program
